# Generated by Django 5.1.3 on 2024-12-09 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('contactNumber', models.IntegerField()),
                ('qualification', models.CharField(max_length=80)),
                ('emailId', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=60)),
                ('dateOfJoin', models.DateField()),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.department')),
            ],
        ),
    ]
